name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x

      - name: Create .env file
        run: |
          echo "PREFIX=!" >> .env
          echo "YOUR_NUMBER=254742063632" >> .env
          echo "MODE=private" >> .env
          echo "WARNINGS=3" >> .env
          echo "YOUR_NAME=FLASH-MD" >> .env
          echo "ANTICALL=on" >> .env
          echo "ANTIDELETE=on" >> .env
          echo "AUTO_REACTION=off" >> .env
          echo "AUTO_READ_STATUS=on" >> .env
          echo "AUTO_LIKE=off" >> .env
          echo "AUTO_READ_DM=on" >> .env
          echo "YOUR_LID=160804129214482" >> .env
          echo "PRESENCE_DM=typing" >> .env
          echo "PRESENCE_GROUP=recording" >> .env
          echo "SESSION=${{ secrets.SESSION }}" >> .env
          echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> .env
          echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME }}" >> .env

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
